export default {
  TODAY_START: 'TODAY_START',
  TODAY_SUCCESS: 'TODAY_SUCCESS',
  TODAY_ERROR: 'TODAY_ERROR',

  TOMORROW_START: 'TOMORROW_START',
  TOMORROW_SUCCESS: 'TOMORROW_SUCCESS',
  TOMORROW_ERROR: 'TOMORROW_ERROR',

  NEXT_7_DAYS_START: 'NEXT_7_DAYS_START',
  NEXT_7_DAYS_SUCCESS: 'NEXT_7_DAYS_SUCCESS',
  NEXT_7_DAYS_ERROR: 'NEXT_7_DAYS_ERROR',

  AFTER_7_DAYS_START: 'AFTER_7_DAYS_START',
  AFTER_7_DAYS_SUCCESS: 'AFTER_7_DAYS_SUCCESS',
  AFTER_7_DAYS_ERROR: 'AFTER_7_DAYS_ERROR',

  BURNED_OUT_START: 'BURNED_OUT_START',
  BURNED_OUT_SUCCESS: 'BURNED_OUT_SUCCESS',
  BURNED_OUT_ERROR: 'BURNED_OUT_ERROR',

  DONE_START: 'DONE_START',
  DONE_SUCCESS: 'DONE_SUCCESS',
  DONE_ERROR: 'DONE_ERROR',
};
