export default {
  GET_PRIORITIES_START: 'createTask/GET_PRIORITIES_START',
  GET_PRIORITIES_SUCCESS: 'createTask/GET_PRIORITIES_SUCCESS',
  GET_PRIORITIES_ERROR: 'createTask/GET_PRIORITIES_ERROR',
};
