export const GET_DATE_TASKS_START = 'GET_DATE_TASKS_START';
export const GET_DATE_TASKS_SUCCESS = 'GET_DATE_TASKS_SUCCESS';
export const GET_DATE_TASKS_ERROR = 'GET_DATE_TASKS_ERROR';

export const GET_STATISTICS_ROLES_START = 'GET_STATISTICS_ROLES_START';
export const GET_STATISTICS_ROLES_SUCCESS = 'GET_STATISTICS_ROLES_SUCCESS';
export const GET_STATISTICS_ROLES_ERROR = 'GET_STATISTICS_ROLES_ERROR';
