export default {
  REGISTRATION_START: 'REGISTRATION_START',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  // LOGOUT_START: 'LOGOUT_START',
  // LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  // LOGOUT_ERROR: 'LOGOUT_ERROR',

  // REFRESH_START: 'REFRESH_START',
  // REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  // REFRESH_ERROR: 'REFRESH_ERROR',
};
