export default {
  REGISTRATION_START: 'auth/REGISTRATION_START',
  REGISTRATION_SUCCESS: 'auth/REGISTRATION_SUCCESS',
  REGISTRATION_ERROR: 'auth/REGISTRATION_ERROR',

  LOGIN_START: 'auth/LOGIN_START',
  LOGIN_SUCCESS: 'auth/LOGIN_SUCCESS',
  LOGIN_ERROR: 'auth/LOGIN_ERROR',

  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',

  // REFRESH_START: 'REFRESH_START',
  // REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  // REFRESH_ERROR: 'REFRESH_ERROR',
  LOGIN_GOOGLE: 'auth/LOGIN_GOOGLE',
};
