export default {
  GET_ROLES_START: 'tasks/roles/GET_ROLES_START',
  GET_ROLES_SUCCESS: 'tasks/roles/GET_ROLES_SUCCESS',
  GET_ROLES_ERROR: 'tasks/roles/GET_ROLES_ERROR',

  ADD_ROLE_START: 'tasks/roles/ADD_ROLE_START',
  ADD_ROLE_SUCCESS: 'tasks/roles/ADD_ROLE_SUCCESS',
  ADD_ROLE_ERROR: 'tasks/roles/ADD_ROLE_ERROR',

  UPDATE_ROLE_START: 'tasks/roles/UPDATE_ROLE_START',
  UPDATE_ROLE_SUCCESS: 'tasks/roles/UPDATE_ROLE_SUCCESS',
  UPDATE_ROLE_ERROR: 'tasks/roles/UPDATE_ROLE_ERROR',

  DELETE_ROLE_START: 'tasks/roles/DELETE_ROLE_START',
  DELETE_ROLE_SUCCESS: 'tasks/roles/DELETE_ROLE_SUCCESS',

  DELETE_ROLE_ERROR: 'tasks/roles/DELETE_ROLE_ERROR',
};
