const styles = {
  modal: {
    top: '50%',
    left: '50%',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
    overlay: {
      backgroundColor: '#e3bd32',
      opacity: '99%',
    },
  },
  xButton: {
    position: 'absolute',
    right: '0',
    top: '0',
    width: '3rem',
    height: '3rem',
    fontSize: '1.5rem',
    fontWeight: '300',
    borderRadius: '100%',
    backgroundColor: '#e3bd32',
    zIndex: '999',
    color: '#fff',
    lineHeight: '3rem',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  closeButton: {
    position: 'absolute',
    right: '0',
    width: '5rem',
    height: '2rem',
    fontSize: '1rem',
    fontWeight: '300',
    borderRadius: '10%',
    backgroundColor: '#e3bd32',
    zIndex: '999',
    color: '#fff',
    lineHeight: '1rem',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  title: {
    textAlign: 'center',
  },
};

export default styles;
