const styles = {
  modal: {
    top: '50%',
    left: '50%',
    right: 'auto',
    bottom: 'auto',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
    overlay: {
      backgroundColor: '#ff6b08',
    },
  },
  xButton: {
    position: 'absolute',
    right: '0',
    top: '0',
    width: '3rem',
    height: '3rem',
    fontSize: '1.5rem',
    fontWeight: '300',
    borderRadius: '100%',
    backgroundColor: '#ff6b08',
    zIndex: '999',
    color: '#fff',
    lineHeight: '3rem',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  closeButton: {
    position: 'absolute',
    right: '0',
    width: '5rem',
    height: '2rem',
    fontSize: '1rem',
    fontWeight: '300',
    borderRadius: '10%',
    backgroundColor: '#ff6b08',
    zIndex: '999',
    color: '#fff',
    lineHeight: '1rem',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  btnAgree: {
    border: 'none',
    cursor: 'pointer',
    color: 'gray-color',
    fontSize: '12px',
    fontFamily: 'font-stack',
    backgroundColor: 'white',
  },
};

export default styles;
